name: Free-up the ephemeral disk
description: Free-up the ephemeral disk of GHA runners for reuse

runs:
  using: composite
  steps:
    - name: Ephemeral disk checks
      shell: bash
      run: |
          set -eux

          # If the rootfs and the ephemeral part are on the same physical disk, it is not possible to wipe
          # the whole disk as the rootfs would be removed as well. Since it is pretty rare for GitHub Action
          # runners to have a single disk, we immediately bail rather than trying to gracefully handle it.
          if [ "$(stat -c '%d' /)" = "$(stat -c '%d' /mnt)" ]; then
            echo "FAIL: rootfs and ephemeral part on the same disk, aborting"
            exit 1
          fi

    - name: Free-up ephemeral disk
      shell: bash
      id: free_ephemeral_disk
      run: |
          set -eux

          # LXD snap holds on to the swap that prevents the clearing of the ephemeral disk
          # https://github.com/canonical/lxd/issues/14768
          if [ -e "/snap/lxd/current" ]; then
            sudo snap remove --purge lxd || true
          fi

          sudo swapoff /mnt/swapfile
          ephemeral_disk="$(findmnt --noheadings --output SOURCE --target /mnt | sed 's/[0-9]\+$//')"
          sudo umount /mnt
          echo "ephemeral_disk=${ephemeral_disk}" >> "${GITHUB_OUTPUT}"
