name: Setup MicroCeph
description: Setup MicroCeph to use the ephemeral disk of GHA runners

inputs:
  microceph-channel:
    description: MicroCeph snap channel to install
    default: "latest/edge"
    required: false
  osd-count:
    description: Number of OSDs to add to MicroCeph
    default: "1"
    required: false
  snap-cache-dir:
    description: Directory to use for snap cache
    default: "/home/runner/snap-cache"
    required: false

runs:
  using: composite
  steps:
    - name: Free-up ephemeral disk
      id: free_ephemeral_disk
      uses: ./.github/actions/free-ephemeral-disk

    - name: Install MicroCeph snap
      shell: bash
      env:
        SNAP_CACHE_DIR: ${{ inputs.snap-cache-dir }}
        SNAP_CHANNEL: ${{ inputs.microceph-channel }}
      run: |
          set -eux
          . "${GITHUB_ACTION_PATH}/setup-microceph.sh"
          install_microceph "${SNAP_CHANNEL}"

    - name: Configure MicroCeph snap
      shell: bash
      env:
        EPHEMERAL_DISK: ${{ steps.free_ephemeral_disk.outputs.ephemeral_disk }}
        INPUTS_OSD_COUNT: ${{ inputs.osd-count }}
      run: |
          set -eux
          . "${GITHUB_ACTION_PATH}/setup-microceph.sh"
          configure_microceph "${EPHEMERAL_DISK}" "${INPUTS_OSD_COUNT}"

    - name: Install ceph-common package
      shell: bash
      run: |
          set -eux
          . "${GITHUB_ACTION_PATH}/setup-microceph.sh"
          install_ceph_common

    - name: Wait for MicroCeph to be ready
      shell: bash
      run: |
          set -eux
          . "${GITHUB_ACTION_PATH}/setup-microceph.sh"
          wait_for_microceph
